# Generated by Django 3.1.4 on 2020-12-04 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("torneio", "0001_initial"),
        ("competidor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="competidor",
            name="torneios",
            field=models.ManyToManyField(to="torneio.Torneio"),
        ),
    ]
