# Generated by Django 3.1.4 on 2020-12-04 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("competidor", "0002_competidor_torneios"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="competidor",
            name="torneios",
        ),
    ]
