# Generated by Django 3.1.4 on 2020-12-03 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Torneio",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_torneio", models.CharField(max_length=120)),
                ("tipo_torneio", models.CharField(max_length=50)),
                ("modalidade", models.CharField(max_length=120)),
            ],
        ),
    ]
