# Generated by Django 3.1.4 on 2020-12-04 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competidor", "0003_remove_competidor_torneios"),
        ("torneio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="torneio",
            name="competidor",
            field=models.ManyToManyField(to="competidor.Competidor"),
        ),
    ]
