# Generated by Django 3.1.4 on 2020-12-05 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("torneio", "0002_torneio_competidor"),
    ]

    operations = [
        migrations.AddField(
            model_name="torneio",
            name="em_andamento",
            field=models.BooleanField(default=False),
        ),
    ]
