# Generated by Django 3.1.4 on 2020-12-06 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competidor", "0003_remove_competidor_torneios"),
        ("torneio", "0003_torneio_em_andamento"),
    ]

    operations = [
        migrations.CreateModel(
            name="Partida",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "num_rodada",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Numero da Rodada"
                    ),
                ),
                (
                    "competidor1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Partida_competidor1",
                        to="competidor.competidor",
                        verbose_name="Competidor1",
                    ),
                ),
                (
                    "competidor2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Partida_competidor2",
                        to="competidor.competidor",
                        verbose_name="Competidor2",
                    ),
                ),
                (
                    "torneio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="torneio.torneio",
                        verbose_name="Torneio",
                    ),
                ),
                (
                    "vencedor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Partida_vencedor",
                        to="competidor.competidor",
                        verbose_name="Competidor2",
                    ),
                ),
            ],
        ),
    ]
